GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "author": "test2",
  "title": "good blog2",
  "url": "https://fullstackopen.com/2",
  "upvotes": 0
}
