GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "author": "test",
  "title": "good blog",
  "url": "https://fullstackopen.com",
  "upvotes": 0
}
