GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "author": "xxx",
  "title": "yyy",
  "url": "https://zzz.zz",
  "upvotes": 2
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "jacek",
  "name": "Jacek",
  "password": "test"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}

###
GET http://localhost:3003/api/users
content-type: application/json

###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "jacek",
  "password": "test"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2VrIiwiaWQiOiI2NTM4MzU2NDJiNGU0NjE5MjdjODEzN2IiLCJpYXQiOjE2OTgyNTA1ODYsImV4cCI6MTY5ODI1NDE4Nn0.sTu4jANdKPqaVjwT1D8nutUFIvNbpO2gWDAqZTPzTDQ

{
  "author": "author",
  "title": "title",
  "url": "https://fullstackopen.com/url",
  "upvotes": 5
}
