GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "author": "xxx",
  "title": "yyy",
  "url": "https://zzz.zz",
  "upvotes": 2
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "jacek",
  "name": "Jacek",
  "password": "test"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}

###
GET http://localhost:3003/api/users
content-type: application/json

###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "jacek",
  "password": "test"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2VrIiwiaWQiOiI2NTM4MzU2NDJiNGU0NjE5MjdjODEzN2IiLCJpYXQiOjE2OTgyNjExMzAsImV4cCI6MTY5ODI2NDczMH0.QGjPuA8-9Q18C5ogJlTtu5usatKbWsqVPmS3AJ7EOPI

{
  "author": "author",
  "title": "title",
  "url": "https://fullstackopen.com/url",
  "upvotes": 5
}

###
DELETE http://localhost:3003/api/blogs/65383cc56d81b139db9c950e
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphY2VrIiwiaWQiOiI2NTM4MzU2NDJiNGU0NjE5MjdjODEzN2IiLCJpYXQiOjE2OTgyNjA2NDYsImV4cCI6MTY5ODI2NDI0Nn0.rImSENTUiYodcrOKnBTHpxsjs0tO8EoTV-Uggu3Qidg